### ISSUE TITLE
Error when connecting to Cassandra

### ISSUE THREAD

**Issue by ander2** [aaronbenz/caspanda#15]
I've just downloaded and installed caspanda and I was trying to run a simple example but I got this error:

>  Traceback
> 
>  (most recent call last):
>   File "caspanda_test.py", line 5, in <module>
>     cpsession = cl.connect('demo_opcua')
>   File "/Users/agy/Working/industry-4.0/caspanda/caspanda/bear.py", line 37, in connect
>     self._sync_metadata(kp)
>   File "/Users/agy/Working/industry-4.0/caspanda/caspanda/bear.py", line 69, in _sync_metadata
>     index_options, index_type, type as cql_type, validator FROM system.schema_columns""")
>   File "cassandra/cluster.py", line 1941, in cassandra.cluster.Session.execute (cassandra/cluster.c:33642)
>   File "cassandra/cluster.py", line 3629, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:69369)
> cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table schema_columns"`

The code I'm triying to run is the following:

```
from caspanda.bear import CasPanda


cl = CasPanda(['localhost'])
cpsession = cl.connect('demo_opcua')
```

Any idea what's wrong?

**Comment by aaronbenz** [comment]
Are you using Cassandra 3.0+?
