### ISSUE TITLE
ImportError: cannot import name '_shutdown_cluster'

### ISSUE THREAD

**Issue by AEDWIP** [aaronbenz/caspanda#16]
Any idea what my problem might be?

thanks

andy

from caspanda.bear import CasPanda
​
cl = CasPanda()
## session = cl.connect()

ImportError                               Traceback (most recent call last)
<ipython-input-1-e582c48601a8> in <module>()
----> 1 from caspanda.bear import CasPanda
      2 
      3 cl = CasPanda()
      4 session = cl.connect()

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/caspanda-0.0.0.4-py3.4.egg/caspanda/bear.py in <module>()
      9 from caspanda.metabear import ColumnMeta, KeyspaceMeta, TableMeta
     10 from cassandra.query import dict_factory
---> 11 from cassandra.cluster import _shutdown_cluster
     12 
     13 from caspanda.bamboo import CassandraFrame

ImportError: cannot import name '_shutdown_cluster'

**Comment by aaronbenz** [comment]
Are you using Cassandra 3.0+?

**Comment by Veni-Technologies** [comment]
@aaronbenz I have got the same issue here - am using Cassandra 3.7.0 

many thanks in advance

**Comment by noeliaoses** [comment]
I'm getting the same error message. Any help will be much appreciated!

**Comment by aprilyichenwang** [comment]
Same error message, thanks in advance.

**Comment by beltran** [comment]
`_shutdown_cluster` is no longer a function in `cassandra.cluster`. This can be solved by removing the line which is importing it, which is unused anyway: https://github.com/aaronbenz/caspanda/blob/master/caspanda/bear.py#L11

**Comment by bertop89** [comment]
Can anybody create a PR?

**Comment by aaronbenz** [comment]
Resolved on form #18
