### ISSUE TITLE
Looks like this project does not work with Cassandra 3.7

### ISSUE THREAD

**Issue by davidwynter** [aaronbenz/caspanda#17]
This query in bear.py is no longer valid

`#gets all of the column data for all tables/keyspaces
        result = self.session.execute("""SELECT keyspace_name, columnfamily_name, column_name, component_index, index_name,
                             index_options, index_type, type as cql_type, validator FROM system.schema_columns""")`

The table system.schema_columns no longer exists. I could not find the columns component_index, index_options, index_type and type anywhere in other tables. columnfamily_name now appears to be table_name in system_schema.columns table along with  keyspace_name and column_name

**Comment by aaronbenz** [comment]
I'm assuming you are using Cassandra 3.0+

If so, I believe you are correct. If you wanted to submit a pull request with a fix I'd be happy to merge.

**Comment by davidwynter** [comment]
Hi,

I researched it a bit further and found other changes required. On balance it was easier to go back to using the straight python driver for cassandra, sorry.
